### ISSUE TITLE
update for laravel5

### ISSUE THREAD

**Issue by lorvent** [summerblue/laravel-blog#3]
Hi,
any idea of updating to laravel 5?

I am sure many people can learn things in l5 if you can update it to l5

**Comment by summerblue** [comment]
In order to upgrade to the version 5, all of the packages this project depends on must be ready too. 

Confide is not ready yet . https://github.com/Zizaco/confide

**Comment by lorvent** [comment]
But i guess you can use l5's built in authentication system

also check https://github.com/Zizaco/confide/issues/448

**Comment by summerblue** [comment]
Not just the authentication system, they're others: https://github.com/summerblue/laravel-blog/blob/master/composer.json#L8-L17

**Comment by lorvent** [comment]
Oh then we may need to wait for some more days :)
